-- Seed data for public.design_process_steps
-- References public.icons using icon_id.

INSERT INTO public.design_process_steps (id, title, slug, description, content, icon_id, sort_order, created_at, updated_at) VALUES
  ('dps-uuid-discovery', 'Discovery & Research', 'discovery-research', 'Understanding your users, business goals, and technical constraints to lay a solid foundation.', '{"objectives": ["Define project scope and objectives", "Conduct user interviews and surveys", "Analyze competitors and market trends"], "deliverables": ["Research synthesis report", "User personas", "Journey maps"]}', 'f1e2d3c4-b5a6-9876-5432-10fedcba9876', 10, NOW(), NOW()),
  ('dps-uuid-strategy', 'Strategy & Ideation', 'strategy-ideation', 'Defining the UX strategy, information architecture, and exploring initial concepts.', '{"objectives": ["Develop UX vision and strategy", "Define information architecture and sitemap", "Brainstorm and sketch initial concepts"], "deliverables": ["UX strategy document", "Sitemap and IA diagrams", "Concept sketches and moodboards"]}', 'c1d2e3f4-a5b6-c7d8-e9f0-a1b2c3d4e5f6', 20, NOW(), NOW()),
  ('dps-uuid-design', 'Design & Prototyping', 'design-prototyping', 'Crafting user flows, wireframes, high-fidelity mockups, and interactive prototypes.', '{"activities": ["User flow mapping", "Wireframing (low and high fidelity)", "UI Design (visuals and branding)", "Interactive prototyping"], "tools": ["Figma", "Adobe XD", "ProtoPie"]}', 'c1d2e3f4-a5b6-c7d8-e9f0-a1b2c3d4e5f6', 30, NOW(), NOW()),
  ('dps-uuid-testing', 'Testing & Iteration', 'testing-iteration', 'Validating designs with users, gathering feedback, and iterating to refine the experience.', '{"activities": ["Usability testing (moderated and unmoderated)", "A/B testing", "Preference testing", "Heuristic evaluation by team"], "outputs": ["Usability test reports", "Actionable feedback summary", "Revised prototypes"]}', 'a1b2c3d4-e5f6-7890-1234-56789abcdef0', 40, NOW(), NOW()),
  ('dps-uuid-develop', 'Development & Handoff', 'development-handoff', 'Collaborating with developers to ensure faithful implementation and providing clear design specifications.', '{"activities": ["Create detailed design specifications", "Developer Q&A sessions", "UI QA and bug tracking", "Asset preparation"], "deliverables": ["Final design specs", "Asset library", "Style guide access"]}', 'd4ad4325-f56b-4cf4-9b10-0003ab4fbd51', 50, NOW(), NOW());

-- Add more design process steps as needed